services:
  - type: web
    name: medplus
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn quickmeds.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quickmeds.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: medplus-db
          property: connectionString
