services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn quickmeds.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quickmeds.settings
      - key: *lv2g8=u%1&jn#nope9c0gokzqjt@=n9vt-#$s#+8fyzi8o97x
        generateValue: true
        # The configuration looks mostly correct, but there are a few issues to fix:
        # 1. The startCommand should use "quickmeds" instead of "yourprojectname"
        # 2. The DJANGO_SETTINGS_MODULE should use "quickmeds" instead of "yourprojectname"
        # 3. The SECRET_KEY configuration is correct with generateValue: true
